name: Convert audio to M4A (replace originals)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"   # cada hora; ajusta si quieres

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          node -v
          npm -v
          ffmpeg -version | head -n 1
          ffprobe -version | head -n 1

      - name: Install deps (ci if lockfile, else install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i --no-fund --no-audit
          fi

      - name: Dry peek candidates (no cambios, solo prueba)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_BUCKET: audios
          SUPABASE_TABLE: recordings
          APPROVED_ONLY: "true"
        run: node scripts/peek.mjs

      - name: Run conversion
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_BUCKET: audios
          SUPABASE_TABLE: recordings
          BATCH_LIMIT: "30"
          APPROVED_ONLY: "true"
          DRY_RUN: "false"   # pon "true" si quieres ensayar sin tocar nada
          BITRATE: "64k"
        run: npm run convert
